#!/bin/bash

# Instructions for new Condo Cluster users:
#  To use this script:
#   1) Save this script as a file named myscript on condo
#   2) On condo, Issue                   
#       qsub  myscript    to submit the job 
#        Use qstat -a to see job status, 
#         Use qdel jobname to delete one of your jobs
#         jobnames are of the form 1234.condo

###########################################
# Output goes to file BATCH_OUTPUT.
# Error output goes to file BATCH_ERRORS.
# If you want the output to go to another file, change BATCH_OUTPUT 
# or BATCH_ERRORS in the following lines to the full path of that file. 

#PBS -N xgb_V1_tune
#PBS -o OUTPUT_CV
#PBS -e ERROR_CV
#PBS -lnodes=1:ppn=16:compute,walltime=04:00:00

# Change to directory from which qsub command was issued 
cd $PBS_O_WORKDIR

module load LAS/python/2.7.10

python cv.py
